### ISSUE TITLE
Add 2 more block view options 

### ISSUE THREAD

**Issue by andrewboon** [boonex/trident#235]
Content + Title
Content + Title + Padding

**Comment by AlexTr** [comment]
It looks you mean blocks without background, since we already have 
"Content + title + background" and "Content + title + background + padding". If there is no background - then there is no design at all, so you can make your own title, background, padding, etc as you need. 

Are you sure you want to add such blocks ?

**Comment by andrewboon** [comment]
Yes, because you can only set your own title for html/custom blocks, not for module blocks. For example, when I want to put a simple login form and join form boxes without background, I can't keep the title, so I can only create another block on top of it to simulate, but this gives a big margin. 

Also, the work "only" is not needed when describing block content combinations. Just use "Content + Title + Background + Padding " format in all combinations, ie "Content" ; "Content + Padding"; "Content + Title" , etc.
